config/routes.rb
Uptimetry::Application.routes.draw do

  match 'billing/post_back' => "billing#post_back", :via => :post, :as => 'billing_post_back'

  resources :plans, :only => [ :create, :index ] do
    collection do
      post :select
    end
  end

  resources :users, :only => [ :new, :create, :update ]
  resources :domains do
    resources :endpoints #, controller: 'domains/endpoints'
  end
  resources :endpoints do
    member do
      get :refresh
      get :remove
    end
  end
  resources :orders

  match 'endpoints/:secret_key/up' => 'endpoints#up'
  match 'endpoints/:secret_key/down' => 'endpoints#down'
  resource :account, :only => [ :show ]
  resource :session, :only => [ :new, :create, :destroy ]
  resources :sessions, :only => [ :new, :create, :destroy ]
  match '/subscriptions/post_back' => 'subscriptions#post_back', :via => :post
  
  namespace :api do
    resource :session, :only => [ :create, :destroy ]
    resources :sessions, :only => [ :create, :destroy ]
    resource :user, :only => [ :show, :update, :destroy ]
    resources :users, :only => :create
    resources :domains
    resources :endpoints
    resources :devices, only: [ :create, :destroy ]
  end

  match 'sign_up' => 'users#new', :as => 'sign_up'
  match 'sign_in' => 'sessions#new', :as => 'sign_in'
  match 'sign_out' => 'sessions#destroy', :via => [:get, :delete], :as => 'sign_out'
  
  # heroku addon api
  post '/heroku/resources' => 'heroku#create'
  put '/heroku/resources/:id' => 'heroku#update'
  delete '/heroku/resources/:id' => 'heroku#destroy'
  post '/heroku/sso' => 'heroku#sso'
  
  root :to => "welcome#index"
end

app/models/endpoint.rb
require 'monitorable'
class Endpoint < ActiveRecord::Base

  include ::Monitorable
  
  belongs_to :domain
  
  attr_accessible :url, :email, :css_selector, :xpath, :retry_count, :retry_delay
  
  validates_presence_of :domain_id, :url, :email
  validates_format_of :url, :with => /http(s)?\:\/\/(.+)(\/)?(.*)/
  # validates_numericality_of :retry_count, minimum: 1, maximum: 5
  # validates_numericality_of :retry_delay, minimum: 10, maximum: 60

  before_create :generate_secret_key
  before_save :init_down_count
  before_save :init_retry_delay
  before_destroy {|obj| Domain.delete(obj.domain_id) if obj.domain!=nil && obj.domain.endpoints.count==1}
  
  def generate_secret_key
    self.secret_key = Digest::SHA1.hexdigest("--#{email}--#{url}--")[0..9]
  end
  
  def init_down_count
    self.down_count = 0
  end
  
  def init_retry_delay
    self.retry_delay = 30 if retry_delay.blank?
  end
  
end

app/controllers/api/endpoints_controller.rb
class Api::EndpointsController < Api::BaseController

  before_filter :authorize
  before_filter :can_access_endpoint?, :only => [ :show, :update, :destroy ]
  before_filter :valid_subscription?, :only => [ :create ]

  def index
    @endpoints = Endpoint.joins(:domain).where(domains: { user_id: current_user.id }).order(:domain_id)
    respond_to do |format|
      format.json { render :json => @endpoints.to_json(:only => [:id,:domain_id,:url,:email,:last_successful_attempt,:up,:css_selector,:xpath,:down_count])}
    end
  end
  
  def create
    @endpoint = Endpoint.new(params[:endpoint])
    @endpoint.user_id = current_user.id
    respond_to do |format|
      if @endpoint.save
        format.json { render :json => @endpoint.to_json(:only => [:id,:domain_id,:url,:email,:css_selector,:xpath,:down_count]), :status => :ok }
      else
        format.json { render :json => { :errors => @endpoint.errors.full_messages }, :status => :unprocessable_entity }
      end
    end
  end
  
  def show
    @endpoint = Endpoint.find(params[:id])
    respond_to do |format|
      format.json { render :json => @endpoint, :status => :success }
    end
  end
  
  def update
    @endpoint = Endpoint.find(params[:id])
    respond_to do |format|
      if @endpoint.update_attributes(params[:endpoint])
        format.json { head :ok }
      else
        format.json { render :json => { :errors => @endpoint.errors.full_messages }, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @endpoint = Endpoint.find(params[:id])
    @endpoint.destroy
    head :ok
  end
  
  private
  
  def can_access_endpoint?
    deny_access unless current_user.endpoint_ids.include?(params[:id].to_i)
  end
  
end

app/controllers/domains/endpoints_controller.rb
class Domains::EndpointsController < ApplicationController

  before_filter :assign_domain
  
  def index
    @endpoints = Endpoint.where(domain_id: @domain.id)
  end
  
  def assign_domain
    @domain = Domain.find(params[:domain_id])
    deny_access unless @domain.user_id==current_user.id
  end
  
end

app/controllers/endpoints_controller.rb
class EndpointsController < ApplicationController

  before_filter :authorize, :except => [ :up, :down ]
  before_filter :assign_endpoint_by_secret_key, :only => [ :up, :down ]
  before_filter :valid_subscription?, :only => [ :create ]
  before_filter :assign_endpoint, :only => [ :show, :edit, :update, :refresh, :remove, :destroy ]
  
  respond_to :html, :js
  
  def index
    @endpoints = Endpoint.includes(:domain).where('domains.user_id = ?',current_user.id).order('domains.name asc, endpoints.url asc')
    respond_with(@endpoints, status: :ok)
  end
  
  def create
    @endpoint = Endpoint.new(params[:endpoint])
    @endpoint.domain = Domain.for_url(@endpoint.url, current_user.id)
    
    if @endpoint.save
      redirect_to domain_path(@endpoint.domain)
    else
      redirect_to new_endpoint_path(endpoint: params[:endpoint]), alert: @endpoint.errors.full_messages
    end
  end

  def new
    @endpoint = Endpoint.new(params[:endpoint])
    respond_with(@endpoint, status: :ok)
  end
  
  def show
    respond_with(@endpoint, status: :ok)
  end
  
  def edit
    respond_with(@endpoint, status: :ok)
  end
  
  def update
    if @endpoint.update_attributes(params[:endpoint])
      redirect_to endpoint_path(@endpoint)
    else
      redirect_to endpoint_path(@endpoint), alert: @endpoint.errors.full_messages
    end
  end
  
  def refresh
    if @endpoint.monitor(@endpoint.url, @endpoint.css_selector, @endpoint.xpath)
      endpoint_is_up
    else
      endpoint_is_down(false)
    end
    respond_to do |format|
      format.html { render :action => :show }
      format.js { render :layout => false }
    end
  end
  
  def remove
    respond_with(@endpoint)
  end
  
  def destroy
    @endpoint.destroy
    
    redirect_to domains_path
  end
  
  # callbacks for IronWorker
  def up
    endpoint_is_up
    head :ok
  end
  
  def down
    endpoint_is_down
    head :ok
  end
  
  private
  
  def assign_endpoint
    @endpoint = Endpoint.find(params[:id])
  end
  
  def assign_endpoint_by_secret_key
    @endpoint = Endpoint.find_by_secret_key(params[:secret_key])
  end
  
  def endpoint_is_up
    @endpoint.up = true
    @endpoint.last_successful_attempt = Time.now
    @endpoint.down_count = 0
    @endpoint.save
  end
  
  def endpoint_is_down(attempt_retry=true)
    if @endpoint.down_count < @endpoint.retry_count
      # failure; schedule a retry
      schedule_retry(@endpoint) if attempt_retry
    else
      # send notice only on last failed retry
      if @endpoint.user.devices.empty?
        # if user has not configured push messaging, send email
        DomainMailer.notify(@endpoint).deliver
      else
        send_notification
      end
    end
    @endpoint.up = false
    @endpoint.down_count = @endpoint.down_count + 1
    @endpoint.save
  end

  def schedule_retry(endpoint)
    return unless Rails.env.production? # only schedule the worker in production env 
    client = IronWorkerNG::Client.new(token: ENV['IRON_WORKER_TOKEN'], project_id: ENV['IRON_WORKER_PROJECT_ID'])
    attrs = { 
      url: endpoint.url, 
      secret_key: endpoint.secret_key, 
      css_selector: endpoint.css_selector,
      xpath: endpoint.xpath
      }
    client.tasks.create('monitor', attrs, {delay: endpoint.retry_delay.seconds})
  end

  def send_notification
    pusher = Grocer.pusher(
      certificate: "config/apns/development.pem",
      gateway: "gateway.sandbox.push.apple.com"
    )
      
    notifications = []
    payload = { endpoint_id: @endpoint.id }
    for device in @endpoint.user.devices
      notification = Grocer::Notification.new(
        device_token: device.token, 
        alert: "Outage Alert", 
        custom: payload
      )
      notifications << notification
    end
    
    notifications.each do |notif|
      pusher.push(notif)
    end
  end
  
end

app/helpers/domains/endpoints_helper.rb
module Domains::EndpointsHelper
end

app/helpers/endpoints_helper.rb
module EndpointsHelper

  def status_for(endpoint)
    if endpoint.up
      "OK"
    elsif endpoint.down_count==1
      "WARN"
    else
      "Last Successful Attempt: " + (endpoint.last_successful_attempt.nil? ? 'Never' : endpoint.last_successful_attempt.to_s(:long))
    end
  end
  
end

app/views/endpoints/_edit.haml
%h1 Edit Site
= form_for @endpoint do |f|
	= render partial: 'form', locals: { f: f }
	= link_to 'Cancel', endpoint_path(@endpoint)

app/views/endpoints/_form.haml
%h2 URL
%p We'll check this URL hourly for public availability.
%label{for: "site[url]"}
	= f.text_field :url, placeholder: 'http://google.com'

%h2 Notification
%p If anything goes wrong, we'll send you a message.
%label{for: "site[email]"}
	= f.text_field :email, placeholder: current_user.email

%h2 Content Matching
%p Sometimes, you need extra peace of mind and you want to confirm the presence of specific HTML elements. Use a CSS selector or XPath expression to match response content.

%label{for: "site[css_selector]"}
	CSS Selector
	= f.text_field :css_selector, placeholder: '#user_email'

%label{for: "site[xpath]"}
	XPath
	= f.text_field :xpath, placeholder: '//input[id=user_email]'

%p= f.submit 'Save Site', class: 'button'

app/views/endpoints/_new.haml
%h1 New URL
= form_for @endpoint do |f|
	= render partial: 'form', locals: { f: f }

app/views/endpoints/_site.haml
%tr
	%td= site.url
	%td= site.email
	%td= status_for site
	%td
		= link_to_function 'edit', "jQuery('#site_#{site.id}').dialog({modal:true,title:'Edit Site',width:'600px'})", :class => 'button wrench'
		= link_to 'delete', site, :confirm => "Are you sure you want to delete #{site.url}? There is no undo.", :method => :delete, :class => 'button trash'
		.modal{:id => "site_#{site.id}", :style => 'display:none'}
			= form_for site do |f|
				%table{:cellpadding => 0, :cellspacing => 0, :border => 0}
					%tr
						%td= f.label :url
						%td= f.text_field :url
					%tr
						%td= f.label :email
						%td= f.text_field :email
					%tr
						%td= f.label :css_selector
						%td= f.text_field :css_selector, :id => "css_selector_#{dom_id(site)}", :onfocus => "jQuery('#xpath_#{dom_id(site)}').val(null)"
					%tr
						%td= f.label :xpath
						%td= f.text_field :xpath, :id => "xpath_#{dom_id(site)}", :onfocus => "jQuery('#css_selector_#{dom_id(site)}').val(null)"
				%p= f.submit 'UPDATE SITE', :class => 'button'

app/views/endpoints/_status.haml
%span.url= @endpoint.up ? "OK" : "OFFLINE"
%span.last= @endpoint.last_successful_attempt.blank? ? "NEVER" : time_ago_in_words(@endpoint.last_successful_attempt) 

app/views/endpoints/edit.haml
= content_for :title, 'Edit Site'
= content_for :nav do
	%li= link_to 'Domains', domains_path, class: 'sites icon current'
	%li= link_to 'Account', account_path, class: 'account icon'

#site= render partial: 'edit'

app/views/endpoints/edit.js.erb
$('#site').html("<%= escape_javascript(render(partial: 'edit')) %>");

app/views/endpoints/index.haml
= content_for :title, 'My Sites'
= content_for :nav do
	%li= link_to 'Domains', domains_path, class: 'sites icon current'
	%li= link_to 'Account', account_path, class: 'account icon'

#sites
	%h1 Sites

	- if @endpoints.empty?
		%p No sites
	- else
		%ul.sites
			- for site in @endpoints
				%li= link_to content_tag(:span, site.url, class: 'url')+content_tag(:span, (site.last_successful_attempt.nil? ? "Never" : time_ago_in_words(site.last_successful_attempt)), class: 'last'), endpoint_path(site)

	- if current_user.may_create_endpoints?
		%p= link_to 'New URL', new_endpoint_path, class: 'button'
	- else
		%p= link_to 'Upgrade to Add More', plans_path, class: 'button'
		#site_panel.modal{:style => 'display:none'}
			= form_for Endpoint.new do |f|
				= f.hidden_field :user_id, :value => current_user.id
				%table{:cellpadding => 0, :cellspacing => 0, :border => 0}
					%tr
						%td= f.label :url
						%td= f.text_field :url, :value => 'http://'
					%tr
						%td= f.label :email
						%td= f.text_field :email, :value => current_user.email
					%tr
						%td Add Content Match
						%td= check_box_tag :content_match, "Yes", false, {:onchange => "if( jQuery('#content_match:checked').val()!==undefined ){ jQuery('#match').show();}else{jQuery('#match, #css, #xpath').hide();jQuery('#site_css_selector, #site_xpath').val(null);}"}
					%tr{:id => "match", :style => "display:none"}
						%td Type
						%td
							= radio_button_tag :match_type, "css", false, {:onchange => "if( jQuery('#match_type_css').attr('checked')!==undefined){jQuery('#css').show();jQuery('#xpath').hide();}else{jQuery('#css').hide();jQuery('#xpath').show();jQuery('#site_css_selector, #site_xpath').val(null);}"}
							= label :match_type, "CSS"
							= radio_button_tag :match_type, "xpath", false, {:onchange => "if( jQuery('#match_type_xpath').attr('checked')!==undefined){jQuery('#css').hide();jQuery('#xpath').show();}else{jQuery('#css').show();jQuery('#xpath').hide();jQuery('#site_css_selector, #site_xpath').val(null);}"}
							= label :match_type, 'XPath'
					%tr{:id => "css", :style => "display:none"}
						%td= f.label :css_selector
						%td= f.text_field :css_selector
					%tr{:id => "xpath", :style => "display:none"}
						%td= f.label :xpath
						%td= f.text_field :xpath
				%p= f.submit 'CREATE SITE', :class => 'button'

app/views/endpoints/new.haml
= content_for :title, 'New URL'
= content_for :nav do
	%li= link_to 'Domains', domains_path, class: 'sites icon current'
	%li= link_to 'Account', account_path, class: 'account icon'

#site= render partial: 'new'

app/views/endpoints/new.js.erb
$('#site').html("<%= escape_javascript(render(partial: 'new')) %>");

app/views/endpoints/refresh.js.erb
jQuery('#site p.status').innerHTML("<%= escape_javascript(render partial: 'status') %>");

app/views/endpoints/remove.haml
= form_for @endpoint, html: { method: :delete } do |f|
	%h1 Remove Site
	%p Are you sure you want to remove this site? There is no undo.
	= f.submit "Yes, Remove It.", class: 'button'
	= link_to 'Cancel', endpoint_path(@endpoint)
	

app/views/endpoints/show.haml
= content_for :title, "Site: #{@endpoint.url.blank? ? "Empty" : @endpoint.url}"
= content_for :nav do
	%li= link_to 'Domains', domains_path, class: 'sites icon current'
	%li= link_to 'Account', account_path, class: 'account icon'

#site
	%h1 Site: 
	%p.url= @endpoint.url

	%h2 Status:
	%p.status= render partial: 'status'
	
	- unless @endpoint.css_selector.blank?
		%h2 CSS Selector:
		%p= @endpoint.css_selector
		
	- unless @endpoint.xpath.blank?
		%h2 XPath:
		%p= @endpoint.xpath

	%p.control
		Actions:
		= link_to 'edit', edit_endpoint_path(@endpoint), class: 'button pencil'
		= link_to 'remove', remove_endpoint_path(@endpoint), class: 'button trash'
		= link_to 'refresh', refresh_endpoint_path(@endpoint), class: 'button refresh'