config/routes.rb
Uptimetry::Application.routes.draw do

  match 'billing/post_back' => "billing#post_back", :via => :post, :as => 'billing_post_back'

  resources :plans, :only => [ :create, :index ] do
    collection do
      post :select
    end
  end

  resources :users, :only => [ :new, :create, :update ]
  resources :domains do
    resources :endpoints #, controller: 'domains/endpoints'
  end
  resources :endpoints do
    member do
      get :refresh
      get :remove
    end
  end
  resources :orders

  match 'endpoints/:secret_key/up' => 'endpoints#up'
  match 'endpoints/:secret_key/down' => 'endpoints#down'
  resource :account, :only => [ :show ]
  resource :session, :only => [ :new, :create, :destroy ]
  resources :sessions, :only => [ :new, :create, :destroy ]
  match '/subscriptions/post_back' => 'subscriptions#post_back', :via => :post
  
  namespace :api do
    resource :session, :only => [ :create, :destroy ]
    resources :sessions, :only => [ :create, :destroy ]
    resource :user, :only => [ :show, :update, :destroy ]
    resources :users, :only => :create
    resources :domains
    resources :endpoints
    resources :devices, only: [ :create, :destroy ]
  end

  match 'sign_up' => 'users#new', :as => 'sign_up'
  match 'sign_in' => 'sessions#new', :as => 'sign_in'
  match 'sign_out' => 'sessions#destroy', :via => [:get, :delete], :as => 'sign_out'
  
  # heroku addon api
  post '/heroku/resources' => 'heroku#create'
  put '/heroku/resources/:id' => 'heroku#update'
  delete '/heroku/resources/:id' => 'heroku#destroy'
  post '/heroku/sso' => 'heroku#sso'
  
  root :to => "welcome#index"
end

app/models/domain.rb
class Domain < ActiveRecord::Base

  belongs_to :user
  has_many :endpoints
  
  validates_presence_of :user_id, :name
  validates_uniqueness_of :name, scope: :user_id
  
  def self.for_url(url,user_id)
    domain_name = URI.parse(url).host rescue nil
    return nil if domain_name.nil?
    re = /^(?:(?>[a-z0-9-]*\.)+?|)([a-z0-9-]+\.(?>[a-z]*(?>\.[a-z]{2})?))$/i
    root_domain = domain_name.gsub(re, '\1').strip
    find_or_create_by_user_id_and_name(user_id, root_domain)  
  end
  
end

app/controllers/api/domains_controller.rb
class Api::DomainsController < Api::BaseController

  before_filter :authorize
  before_filter :can_access_domain?, :only => [ :show, :update, :destroy ]
  before_filter :valid_subscription?, :only => [ :create ]

  def index
    @domains = current_user.domains
    respond_to do |format|
      format.json { render :json => @domains.to_json(:only => [:id,:name])}
    end
  end
  
  def create
    @domain = Domain.new(params[:domain])
    @domain.user_id = current_user.id
    respond_to do |format|
      if @domain.save
        format.json { render :json => @domain.to_json(:only => [:id,:name]), :status => :ok }
      else
        format.json { render :json => { :errors => @domain.errors.full_messages }, :status => :unprocessable_entity }
      end
    end
  end
  
  def show
    @domain = Domain.find(params[:id])
    respond_to do |format|
      format.json { render :json => @domain, :status => :success }
    end
  end
  
  def update
    @domain = Domain.find(params[:id])
    respond_to do |format|
      if @domain.update_attributes(params[:domain])
        format.json { head :ok }
      else
        format.json { render :json => { :errors => @domain.errors.full_messages }, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @domain = Domain.find(params[:id])
    @domain.destroy
    head :ok
  end
  
  private
  
  def can_access_domain?
    deny_access unless current_user.domain_ids.include?(params[:id].to_i)
  end
  
end

app/controllers/domains/endpoints_controller.rb
class Domains::EndpointsController < ApplicationController

  before_filter :assign_domain
  
  def index
    @endpoints = Endpoint.where(domain_id: @domain.id)
  end
  
  def assign_domain
    @domain = Domain.find(params[:domain_id])
    deny_access unless @domain.user_id==current_user.id
  end
  
end

app/controllers/domains_controller.rb
class DomainsController < ApplicationController

  before_filter :authorize
  before_filter :assign_collection, only: :index
  before_filter :assign_object, only: :show
  
  def index
  end
  
  def show
  end
  
  def assign_collection
    @domains = Domain.includes(:endpoints).where(user_id: current_user.id)
  end
  
  def assign_object
    @domain = Domain.includes(:endpoints).find(params[:id])
  end

end

app/helpers/domains/endpoints_helper.rb
module Domains::EndpointsHelper
end

app/helpers/domains_helper.rb
module DomainsHelper
end

app/views/domains/index.haml
= content_for :title, 'My Sites'
= content_for :nav do
	%li= link_to 'Domains', domains_path, class: 'sites icon current'
	%li= link_to 'Account', account_path, class: 'account icon'

#sites
	%h1 Domains

	- if @domains.empty?
		%p No domains
	- else
		%ul.sites
			- for domain in @domains
				%li= link_to content_tag(:span, domain.name, class: 'url')+content_tag(:span, "#{domain.endpoints.count} URLs", class: 'last'), domain_path(domain)

	- if current_user.may_create_endpoints?
		%p= link_to 'New URL', new_endpoint_path, class: 'button'
	- else
		%p= link_to 'Upgrade to Add More', plans_path, class: 'button'
		#site_panel.modal{:style => 'display:none'}
			= form_for Endpoint.new do |f|
				= f.hidden_field :user_id, :value => current_user.id
				%table{:cellpadding => 0, :cellspacing => 0, :border => 0}
					%tr
						%td= f.label :url
						%td= f.text_field :url, :value => 'http://'
					%tr
						%td= f.label :email
						%td= f.text_field :email, :value => current_user.email
					%tr
						%td Add Content Match
						%td= check_box_tag :content_match, "Yes", false, {:onchange => "if( jQuery('#content_match:checked').val()!==undefined ){ jQuery('#match').show();}else{jQuery('#match, #css, #xpath').hide();jQuery('#site_css_selector, #site_xpath').val(null);}"}
					%tr{:id => "match", :style => "display:none"}
						%td Type
						%td
							= radio_button_tag :match_type, "css", false, {:onchange => "if( jQuery('#match_type_css').attr('checked')!==undefined){jQuery('#css').show();jQuery('#xpath').hide();}else{jQuery('#css').hide();jQuery('#xpath').show();jQuery('#site_css_selector, #site_xpath').val(null);}"}
							= label :match_type, "CSS"
							= radio_button_tag :match_type, "xpath", false, {:onchange => "if( jQuery('#match_type_xpath').attr('checked')!==undefined){jQuery('#css').hide();jQuery('#xpath').show();}else{jQuery('#css').show();jQuery('#xpath').hide();jQuery('#site_css_selector, #site_xpath').val(null);}"}
							= label :match_type, 'XPath'
					%tr{:id => "css", :style => "display:none"}
						%td= f.label :css_selector
						%td= f.text_field :css_selector
					%tr{:id => "xpath", :style => "display:none"}
						%td= f.label :xpath
						%td= f.text_field :xpath
				%p= f.submit 'CREATE SITE', :class => 'button'

app/views/domains/show.haml
= content_for :title, 'My Sites'
= content_for :nav do
	%li= link_to 'Domains', domains_path, class: 'sites icon current'
	%li= link_to 'Account', account_path, class: 'account icon'

#sites
	%h1 Domain: #{@domain.name}

	- if @domain.endpoints.empty?
		%p No URLs
	- else
		%ul.sites
			- for endpoint in @domain.endpoints
				%li= link_to content_tag(:span, endpoint.url, class: 'url')+content_tag(:span, (endpoint.last_successful_attempt.nil? ? "Never" : time_ago_in_words(endpoint.last_successful_attempt)), class: 'last'), endpoint_path(endpoint)

	- if current_user.may_create_endpoints?
		%p= link_to 'New URL', new_endpoint_path, class: 'button'
	- else
		%p= link_to 'Upgrade to Add More', plans_path, class: 'button'
		#site_panel.modal{:style => 'display:none'}
			= form_for Endpoint.new do |f|
				= f.hidden_field :user_id, :value => current_user.id
				%table{:cellpadding => 0, :cellspacing => 0, :border => 0}
					%tr
						%td= f.label :url
						%td= f.text_field :url, :value => 'http://'
					%tr
						%td= f.label :email
						%td= f.text_field :email, :value => current_user.email
					%tr
						%td Add Content Match
						%td= check_box_tag :content_match, "Yes", false, {:onchange => "if( jQuery('#content_match:checked').val()!==undefined ){ jQuery('#match').show();}else{jQuery('#match, #css, #xpath').hide();jQuery('#site_css_selector, #site_xpath').val(null);}"}
					%tr{:id => "match", :style => "display:none"}
						%td Type
						%td
							= radio_button_tag :match_type, "css", false, {:onchange => "if( jQuery('#match_type_css').attr('checked')!==undefined){jQuery('#css').show();jQuery('#xpath').hide();}else{jQuery('#css').hide();jQuery('#xpath').show();jQuery('#site_css_selector, #site_xpath').val(null);}"}
							= label :match_type, "CSS"
							= radio_button_tag :match_type, "xpath", false, {:onchange => "if( jQuery('#match_type_xpath').attr('checked')!==undefined){jQuery('#css').hide();jQuery('#xpath').show();}else{jQuery('#css').show();jQuery('#xpath').hide();jQuery('#site_css_selector, #site_xpath').val(null);}"}
							= label :match_type, 'XPath'
					%tr{:id => "css", :style => "display:none"}
						%td= f.label :css_selector
						%td= f.text_field :css_selector
					%tr{:id => "xpath", :style => "display:none"}
						%td= f.label :xpath
						%td= f.text_field :xpath
				%p= f.submit 'CREATE SITE', :class => 'button'