config/routes.rb
Uptimetry::Application.routes.draw do

  match 'billing/post_back' => "billing#post_back", :via => :post, :as => 'billing_post_back'

  resources :plans, :only => [ :create, :index ] do
    collection do
      post :select
    end
  end

  resources :users, :only => [ :new, :create, :update ]
  resources :domains do
    resources :endpoints #, controller: 'domains/endpoints'
  end
  resources :endpoints do
    member do
      get :refresh
      get :remove
    end
  end
  resources :orders

  match 'endpoints/:secret_key/up' => 'endpoints#up'
  match 'endpoints/:secret_key/down' => 'endpoints#down'
  resource :account, :only => [ :show ]
  resource :session, :only => [ :new, :create, :destroy ]
  resources :sessions, :only => [ :new, :create, :destroy ]
  match '/subscriptions/post_back' => 'subscriptions#post_back', :via => :post
  
  namespace :api do
    resource :session, :only => [ :create, :destroy ]
    resources :sessions, :only => [ :create, :destroy ]
    resource :user, :only => [ :show, :update, :destroy ]
    resources :users, :only => :create
    resources :domains
    resources :endpoints
    resources :devices, only: [ :create, :destroy ]
  end

  match 'sign_up' => 'users#new', :as => 'sign_up'
  match 'sign_in' => 'sessions#new', :as => 'sign_in'
  match 'sign_out' => 'sessions#destroy', :via => [:get, :delete], :as => 'sign_out'
  
  # heroku addon api
  post '/heroku/resources' => 'heroku#create'
  put '/heroku/resources/:id' => 'heroku#update'
  delete '/heroku/resources/:id' => 'heroku#destroy'
  post '/heroku/sso' => 'heroku#sso'
  
  root :to => "welcome#index"
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController

  before_filter :authorize, :only => [ :create, :select ]
  before_filter :retrieve_plans, :only => :index
  
  def index
  end

  def create
    customer = Stripe::Customer.create(email: current_user.email, plan: params[:plan][:id], card: params[:plan][:token])

    current_user.site_allowance = User::SUBSCRIPTION_PLANS[params[:plan][:id]]

    current_user.customer_reference = customer.id
    current_user.card_last_four = customer.active_card.last4
    current_user.card_exp_month = customer.active_card.exp_month
    current_user.card_exp_year = customer.active_card.exp_year
    current_user.card_exp_month = customer.active_card.exp_month
    current_user.save
      
    redirect_to domains_path, :notice => "Your subscription is ready to use"
  rescue Stripe::InvalidRequestError => e
    redirect_to plans_path, :alert => e.message
  end
  
  def select
    allowance = User::SUBSCRIPTION_PLANS[params[:plan][:id]] or 0
    if allowance >= current_user.endpoints.count
      customer = Stripe::Customer.retrieve(current_user.customer_reference)
      customer.update_subscription(plan: params[:plan][:id], prorate: true)

      current_user.site_allowance = allowance
      current_user.save

      redirect_to plans_path, :notice => "Your subscription has been updated."
    else
      redirect_to plans_path, :alert => "You have too many URLs for that plan."
    end
  end
  
  private
  
  def retrieve_plans
    @plans = Stripe::Plan.all.data.sort {|x,y| x.amount <=> y.amount}
  end
  
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/views/plans/index.haml
= content_for :title, 'Available Plans'
- if signed_in?
	= content_for :nav do
		%li= link_to 'Domains', domains_path, class: 'sites icon'
		%li= link_to 'Account', account_path, class: 'account icon current'
		
#plans
	%h1 Available Plans
	%p 
		All plans include hourly URL monitoring and email notification.
		%br
		You can also validate content using CSS Selector or XPath.
	%table
		%tr
			%th PLAN
			%th VALUE
			%th MONTHLY
			- if signed_in?
				%th
		- for plan in @plans
			- allowance = User::SUBSCRIPTION_PLANS[plan.id]
			%tr
				%td.name= plan.name
				%td up to #{allowance} URLs
				%td= number_to_currency(plan.amount / 100.0)
				- if signed_in?
					- if current_user.customer_reference.blank?
						%td
							%p= link_to_function 'Choose this Plan', "selectPlan('#{plan.id}', #{plan.amount}, '#{number_to_currency(plan.amount / 100.0)}')", class: 'button'
					- else
						%td
							- if current_user.site_allowance == allowance
								This is your current plan
							- elsif current_user.endpoints.count < allowance
								= form_for :plan, url: select_plans_path do |f|
									= f.hidden_field :id, value: plan.id
									%p= f.submit 'Change to this Plan', class: 'button'
							- else
								You must remove #{current_user.endpoints.count-allowance} URLs first
					
	- if signed_in?
		#credit_card{style: 'display:none'}
			= form_for :plan, url: plans_path, html: { id: "payment_form" } do |f|
				%p.errors
				= f.hidden_field :id
				= f.hidden_field :amount, class: 'card-amount'
				= f.hidden_field :token
				%p.amount
				%p
					%label Card Number
					%input{type: "text", size: 20, autocomplete: false, class: 'card-number'}
				%p
					%label Expiration Date (MM / YYYY)
					%input{type: "text", size: 2, autocomplete: false, class: 'card-exp-month'}
					%span /
					%input{type: "text", size: 4, autocomplete: false, class: 'card-exp-year'}
				%p
					%label CVV
					%input{type: "text", size: 3, autocomplete: false, class: 'card-cvc'}
				%p= f.submit "Checkout", class: 'button'
	- else
		%p= link_to "Subscribe Today", sign_up_path, class: 'button'