config/routes.rb
Uptimetry::Application.routes.draw do

  match 'billing/post_back' => "billing#post_back", :via => :post, :as => 'billing_post_back'

  resources :plans, :only => [ :create, :index ] do
    collection do
      post :select
    end
  end

  resources :users, :only => [ :new, :create, :update ]
  resources :domains do
    resources :endpoints #, controller: 'domains/endpoints'
  end
  resources :endpoints do
    member do
      get :refresh
      get :remove
    end
  end
  resources :orders

  match 'endpoints/:secret_key/up' => 'endpoints#up'
  match 'endpoints/:secret_key/down' => 'endpoints#down'
  resource :account, :only => [ :show ]
  resource :session, :only => [ :new, :create, :destroy ]
  resources :sessions, :only => [ :new, :create, :destroy ]
  match '/subscriptions/post_back' => 'subscriptions#post_back', :via => :post
  
  namespace :api do
    resource :session, :only => [ :create, :destroy ]
    resources :sessions, :only => [ :create, :destroy ]
    resource :user, :only => [ :show, :update, :destroy ]
    resources :users, :only => :create
    resources :domains
    resources :endpoints
    resources :devices, only: [ :create, :destroy ]
  end

  match 'sign_up' => 'users#new', :as => 'sign_up'
  match 'sign_in' => 'sessions#new', :as => 'sign_in'
  match 'sign_out' => 'sessions#destroy', :via => [:get, :delete], :as => 'sign_out'
  
  # heroku addon api
  post '/heroku/resources' => 'heroku#create'
  put '/heroku/resources/:id' => 'heroku#update'
  delete '/heroku/resources/:id' => 'heroku#destroy'
  post '/heroku/sso' => 'heroku#sso'
  
  root :to => "welcome#index"
end

app/views/layouts/_flash.haml
%h4 Errors
%ul
	- for error in errors
		%li= error

app/views/layouts/application.haml
!!!
%html
	%head
		%title 
			uptimetry -
			= yield(:title)
		%script{:src => "http://www.google.com/jsapi?key=ABQIAAAAPxTP6_umMHWyfMXHRo_PQBSEfduqM-1DVSJvrAuG-sXMl3D3XxRzHgplRb-82VvQp6BVNPn5n6zyAQ", :type => "text/javascript"}
		%link{:rel => "stylesheet", :href => "http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.2/themes/eggplant/jquery-ui.css", :type => "text/css"}
		%link{:rel => "icon", :type => "image/png", :href => "/assets/favicon.ico"}
		= stylesheet_link_tag 'application'
		= csrf_meta_tag
		%script{ :type => "text/javascript", :src => "https://js.stripe.com/v1/"}
		%script{ :type => "text/javascript"}
			Stripe.setPublishableKey("#{ENV['STRIPE_PUBLIC']}");
		= javascript_include_tag 'application'
		%script{:type => "text/javascript"}
			var _gaq = _gaq || [];
			_gaq.push(['_setAccount', 'UA-4535281-5']);
			_gaq.push(['_trackPageview']);

			(function() {
			var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
			ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
			var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
			})();

%body
	- if cookies[:'heroku-nav-data']
		= raw HerokuAddon.nav
    
	#header
		%ul#menu
			%li#logo
				= link_to 'up • tīm • e • try', root_path
				%div -noun
				%p the practice or profession of examining the health and well-being of a website
			= yield(:nav)
	
	#content
		#errors= render(partial: 'layouts/flash', locals: { errors: flash[:alert] }) if flash[:alert]
		= yield
	
	#footer
		- if signed_in?
			%p= link_to 'SIGN OUT', sign_out_path
			
		© Copyright 2012 Migrant Studios. All Rights Reserved.
		%br
		Uptimetry is a trademark of Migrant Studios

app/views/layouts/application.js.erb
<% if flash[:alert].blank? || flash[:alert].empty? -%>
$('#errors').html(null);
$('#errors').hide();
<% else -%>
$('#errors').html("<%= escape_javascript(render(partial: 'layouts/flash', locals: { errors: flash[:alert] })) %>");
$('#errors').show();
<% end -%>
<%= yield %>
jqueryHooks();

app/views/layouts/users.haml
!!!
%html
	%head
		%title 
			uptimetry -
			= yield(:title)
		%script{:src => "http://www.google.com/jsapi?key=ABQIAAAAPxTP6_umMHWyfMXHRo_PQBSEfduqM-1DVSJvrAuG-sXMl3D3XxRzHgplRb-82VvQp6BVNPn5n6zyAQ", :type => "text/javascript"}
		%link{:rel => "stylesheet", :href => "http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.2/themes/eggplant/jquery-ui.css", :type => "text/css"}
		= stylesheet_link_tag 'style'
		= javascript_include_tag :defaults
		= csrf_meta_tag
		%script{ :type => "text/javascript", :charset => "utf-8"}
			google.load("jquery","1.4.2");
			google.load("jqueryui","1.8.2");
		%script{ :type => "text/javascript", :charset => "utf-8"}
			jQuery.noConflict();
			jQuery(document).ready( function() {
			jQuery('.button.trash').button({icons:{primary:'ui-icon-trash'},text:false});
			jQuery('.button.wrench').button({icons:{primary:'ui-icon-wrench'},text:false});
			jQuery('.button').button();
			jQuery('.datepicker').datepicker();
			});
		%script{:type => "text/javascript"}
			var _gaq = _gaq || [];
			_gaq.push(['_setAccount', 'UA-4535281-5']);
			_gaq.push(['_trackPageview']);

			(function() {
			var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
			ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
			var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
			})();

%body
	#header
		%ul#menu
			%li#logo
				= link_to 'up • tīm • e • try', root_path
				%div -noun
				%p the practice or profession of examining the health and well-being of a website
			= yield(:nav)
	
	#content
		- if flash[:notice]
			.ui-state-highlight
				%span{:style => "float: left; margin-right: 0.3em;", :class => 'ui-icon ui-icon-info'}
				= flash[:notice]
		- if flash[:alert]
			.ui-state-error
				%span{:style => "float: left; margin-right: 0.3em;", :class => 'ui-icon ui-icon-alert'}
				= flash[:alert]
		
		= yield
	
	#footer
		© Copyright 2012 Migrant Studios LLC. All Rights Reserved.
		%br
		Uptimetry is a trademark of Migrant Studios LLC

app/views/layouts/welcome.haml
!!!
%html
	%head
		%title 
			uptimetry -
			= yield(:title)
		%script{:src => "http://www.google.com/jsapi?key=ABQIAAAAPxTP6_umMHWyfMXHRo_PQBSEfduqM-1DVSJvrAuG-sXMl3D3XxRzHgplRb-82VvQp6BVNPn5n6zyAQ", :type => "text/javascript"}
		%link{:rel => "stylesheet", :href => "http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.2/themes/eggplant/jquery-ui.css", :type => "text/css"}
		= stylesheet_link_tag 'public'
		= csrf_meta_tag
		%script{ :type => "text/javascript", :charset => "utf-8"}
			google.load("jquery","1.4.2");
			google.load("jqueryui","1.8.2");
		%script{ :type => "text/javascript", :charset => "utf-8"}
			jQuery.noConflict();
			jQuery(document).ready( function() {
			jQuery('.button.trash').button({icons:{primary:'ui-icon-trash'},text:false});
			jQuery('.button.wrench').button({icons:{primary:'ui-icon-wrench'},text:false});
			jQuery('.button').button();
			jQuery('.datepicker').datepicker();
			});
		%script{:type => "text/javascript"}
			var _gaq = _gaq || [];
			_gaq.push(['_setAccount', 'UA-4535281-5']);
			_gaq.push(['_trackPageview']);

			(function() {
			var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
			ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
			var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
			})();

%body
	#header
		#menu
			%ul
				%li#logo
					= link_to 'up • tīm • e • try', root_path
					%div -noun
					%p the practice or profession of examining the health and well-being of a website
	
	- if flash[:notice]
		.ui-state-highlight
			%span{:style => "float: left; margin-right: 0.3em;", :class => 'ui-icon ui-icon-info'}
			= flash[:notice]
	- if flash[:alert]
		.ui-state-error
			%span{:style => "float: left; margin-right: 0.3em;", :class => 'ui-icon ui-icon-alert'}
			= flash[:alert]
		
	#content
		= yield
	
	#footer
		© Copyright 2012 Migrant Studios LLC. All Rights Reserved.
		%br
		Uptimetry is a trademark of Migrant Studios LLC